### ISSUE TITLE
rack-pagespeed should not minify the javascripts for each requests

### ISSUE THREAD

**Issue by mcollina** [juliocesar/rack-pagespeed#16]
Currently the javascripts minification is somewhat expensive and its run at every single page load, but this slow down the response time (something we do want to speed-up, right?).

**Comment by juliocesar** [comment]
See this: [http://rack-pagespeed-preso.heroku.com/#caveats.md](http://rack-pagespeed-preso.heroku.com/#caveats.md).

The idea is to have rack-pagespeed run behind a webserver, which I'm expecting to be configured at least to issue HTTP 304 should a page have not been modified (most sane HTTP servers do it by default). This conditional GET won't even reach your stack, thus the page won't be reprocessed every time.

However, I'm happy to take a look if you're having _massive_ problems, as in it if's adding something in the order of seconds to the page render. It kind of figures it's expensive, since it'll run the minifier for each JS it finds, though that should be alleviated if you're also running `combine_javascripts`.

**Comment by mcollina** [comment]
Well, I'm stretching the capabilities of your gem :).
I'm building a mobile web application using Sencha Touch, and I'm minifying something like ~450 KB of custom javascript code plus ~370 KB of the framework (which is already minified, but I couldn't exclude it): all that adds 8 seconds to my response time on an Amazon EC2 small instance (on my laptop only 2 seconds). I'm already using the combine_javascripts filter, 
Moreover, as the content on the page is relative to the user displaying it, I need to render the page at least once per user, so I could cache from the second time the user displays it, but it's not enough. 

I start thinking that in this kind of applications I should minify it at deploy time, and forgot real time minification. What do you think?

**Comment by juliocesar** [comment]
It might be the way to go, bundling/minifying at deploy time, in your case. It makes sense that at some point it will get slow.

I still think this could be solved by using something like [Varnish](http://www.varnish-cache.org/) in front of your application stack. That's more or less what I had in mind when I wrote rack-pagespeed. But anyway, the point is making things easy. If using [Jammit](http://documentcloud.github.com/jammit/) proves to be easy as well, I say go for it.

**Comment by mcollina** [comment]
Well, I'm currently using the old school mod_cache of Apache, which it's based on the same principles and gives really good response time for my current load. I'm using http conditional get heavily, so I completely understand your point.
Conditional gets are really good for "standard" content, i.e. content that doesn't change at each request or by different request parameters. My case it's quite edgy, as we are serving different mobile websites through different uris, but with the very same codebase.
In this approach I need to warm up the cache before the real client hit, and doing it at deploy time it's quite cheap :).

Thanks foor the good work!

**Comment by juliocesar** [comment]
Cool, sounds good. Yeah, there's no escaping the fact that at some point it will get slow, specially if you have that many JavaScripts.

Thanks for the feedback!
