### ISSUE TITLE
:redis store throwing error

### ISSUE THREAD

**Issue by brandonweiss** [juliocesar/rack-pagespeed#26]
I may have found another bug. This works:

```
store :redis
```

But this does not:

```
store :redis => 'localhost:6379'
```

The error I'm getting is `redis-2.2.0/lib/redis/client.rb:8:in '[]': can't convert Symbol into Integer (TypeError)`

I spent some time trying to trace the problem. I kind of figured it out, but it's unclear if this is a bug in rack-pagespeed or the redis client.

First, at `lib/rack/pagespeed/store/redis.rb:13` you're passing in a hash with the key `:address`, but I think redis is expecting `:host`. Changing this won't solve the problem, so it's unrelated, however I believe this would force the redis client to always use localhost?

The actual problem appears to be with the `options` variable at `redis-2.2.0/lib/redis/client.rb:8`. If I `puts options` before `[:path]` gets called on it, I see two outputs.

`{:host=>"localhost", :port=>6379, :password=>nil}
localhost:6379`

The second one is a string, which is why the error is happening. But I'm not sure what this means. At first it would seem that a client is being created twice, once correctly and then a second time incorrectly. And the fact that the second time a string of that format is being passed in seems to indicate that it's happening in rack-pagespeed, but I can't figure out where or how.

**Comment by juliocesar** [comment]
Hey Brandon,

I'm sure you probably sorted it out by now (or perhaps even went for another solution). Just responding to let you know that the problem is fixed. Basically whenever you pass options to a store mechanism, such as:

```
store redis: { host: 'localhost', port: 6379 }
```

It'll pass those options straight to the library in charge of handing it (in this case the `redis` gem). The example above (Ruby 1.9) works. Make sure you fetch the latest version (1.1.1) for it.

Thanks for the report!
