### ISSUE TITLE
Clearing Existing Bundles Forces Regeneration of Bundles on Each Request

### ISSUE THREAD

**Issue by logicaltext** [juliocesar/rack-pagespeed#3]
Doesn't [clearing existing bundles](http://github.com/juliocesar/rack-bundle/commit/e6c7d5995bab4f4d91852d95ea80b7e6a49ef108#L1R8) remove any attempts to improve performance? Since Rack::Bundle is called on every request, which in turn calls `FileSystemStore.new` (providing you're using the FileSystemStore), all previously generated bundles will be destroyed on every request. I thought the whole point of generating bundles with hashed fingerprints was to avoid regenerating bundles on subsequent requests.

On a side note, just in case you did want the hashed fingerprints to be meaningful, I'm not sure that they can be [generated using the filename alone](http://github.com/juliocesar/rack-bundle/commit/1a8c9bb19a0ed1aa8a1e1646ccd1d3ce45f3a9e3#diff-1). Because when you make a change to the file, the generated hash would stay the same. If, of course, you're going to stick with clearing the bundles on every request, then this doesn't matter! But otherwise I would think about generating the hashes in a different way (perhaps using file modified times, as [I tried here](http://github.com/logicaltext/rack-bundle/commit/38f37c7987be6093eed503e85f9aabdc8a0e6dc0#L1R19)).

I hope this all makes sense, and I apologize if I'm misunderstanding something!

**Comment by juliocesar** [comment]
Hello!

Rack::Bundle sets it's storage mechanism on #initialize, which only gets executed when the application boots up. So clearing up will only happen at that stage. That was always the case with DatabaseStorage by the way (create_table! forcibly re-creates the table every time it gets instanced).

I've always wanted to use file names to generate the hash instead of file contents for 2 reasons: it's a heck of a lot faster than reading the contents of all the Javascript files on every request (that's what was happening until now), and _in theory_, people should always include the version of a Javascript library in the file name. Now I agree that _relying_ on this last bit was very naive of my part. I'll make sure I throw the file mtime in the mix on my next commit.

Thanks!

**Comment by logicaltext** [comment]
Thanks for the response, and sorry for misunderstanding.

> Rack::Bundle sets it's storage mechanism on #initialize, which only gets executed when the application boots up. So clearing up will only happen at that stage.

Of course that's the case. I don't know why I was confusing `initialize` with `call`.

>  ...people should always include the version of a Javascript library in the file name.

Right, but people might be including their own JS which aren't libraries, such as `application.js`.

> I'll make sure I throw the file mtime in the mix on my next commit.

Sounds good.

Have you also considered [serving the bundles via Rack::File](http://github.com/logicaltext/rack-bundle/commit/c42e3d59c2bd5223d7a0ef48ee766886f4e49d63)? You should see performance improvements there as well.

**Comment by juliocesar** [comment]
Yeah, I'm aware Rails has these conventions, none of them that I think are any good, but that's besides the point. My latest push includes a change that takes the file mtime into consideration when generating the hash.

Cheers.
